-- CreateEnum
CREATE TYPE "public"."Reporter" AS ENUM ('expert', 'transporteur', 'autre');

-- CreateEnum
CREATE TYPE "public"."Cause" AS ENUM ('production', 'pompe', 'autre_cause', 'exposition_sinto', 'transporteur', 'autre');

-- CreateEnum
CREATE TYPE "public"."ReturnStatus" AS ENUM ('draft', 'awaiting_physical', 'received_or_no_physical');

-- DropIndex
DROP INDEX "public"."tenants_name_key";

-- AlterTable
ALTER TABLE "public"."Customers" DROP COLUMN "AnonymizationInactiveDate",
DROP COLUMN "AnonymizationLogId",
DROP COLUMN "ApprovedDateCDN",
DROP COLUMN "ApprovedUserIdCDN",
DROP COLUMN "AveragePaymentDays",
DROP COLUMN "City",
DROP COLUMN "Class",
DROP COLUMN "CountryId",
DROP COLUMN "CreditHold",
DROP COLUMN "CreditLimit",
DROP COLUMN "CustType",
DROP COLUMN "DiscList",
DROP COLUMN "Discount",
DROP COLUMN "DiscountListsByClassId",
DROP COLUMN "EDIIdentifier",
DROP COLUMN "FOB",
DROP COLUMN "FirstNameContact",
DROP COLUMN "FixedPrice",
DROP COLUMN "GlVerifyTypeTax",
DROP COLUMN "Industry",
DROP COLUMN "IsApprovedCDN",
DROP COLUMN "IsInPosList",
DROP COLUMN "Langid",
DROP COLUMN "LastModificationDate",
DROP COLUMN "LastNameContact",
DROP COLUMN "Line1",
DROP COLUMN "Line2",
DROP COLUMN "PAPEmail",
DROP COLUMN "PAPFax",
DROP COLUMN "PAPFinancialbankid",
DROP COLUMN "PAPSendtype",
DROP COLUMN "PAPaccountname",
DROP COLUMN "PAPaccountnbr",
DROP COLUMN "PAPtransit",
DROP COLUMN "POreq",
DROP COLUMN "PartialDelivery",
DROP COLUMN "PaymentMethodId",
DROP COLUMN "PriceList",
DROP COLUMN "PrjPrefix",
DROP COLUMN "ShippingCondition",
DROP COLUMN "Shipvia",
DROP COLUMN "StateId",
DROP COLUMN "Statement",
DROP COLUMN "Status",
DROP COLUMN "Taxable",
DROP COLUMN "Terms",
DROP COLUMN "ZipCode",
DROP COLUMN "_isinvoicesend",
DROP COLUMN "_model",
DROP COLUMN "affiliatecustid",
DROP COLUMN "amount",
DROP COLUMN "approbcrid",
DROP COLUMN "ar_account",
DROP COLUMN "billtoid",
DROP COLUMN "businessname",
DROP COLUMN "carrid",
DROP COLUMN "cellulaire",
DROP COLUMN "cieentityid",
DROP COLUMN "cieid",
DROP COLUMN "ciesectorid",
DROP COLUMN "codegeo",
DROP COLUMN "contact",
DROP COLUMN "contactIdHubSpot",
DROP COLUMN "createdDate",
DROP COLUMN "createddatenew",
DROP COLUMN "currid",
DROP COLUMN "custCieid",
DROP COLUMN "daysforaverage",
DROP COLUMN "directdiscount",
DROP COLUMN "discountid",
DROP COLUMN "dutybrokercode",
DROP COLUMN "edipartnerid",
DROP COLUMN "elevage",
DROP COLUMN "email",
DROP COLUMN "emplid",
DROP COLUMN "expirationupa",
DROP COLUMN "fax",
DROP COLUMN "frais",
DROP COLUMN "freqrel",
DROP COLUMN "geoLocation",
DROP COLUMN "glaracc",
DROP COLUMN "glarconversion",
DROP COLUMN "instfinancial",
DROP COLUMN "interest",
DROP COLUMN "interexp",
DROP COLUMN "internalcust",
DROP COLUMN "invoicecontact",
DROP COLUMN "invoicesendtype",
DROP COLUMN "irsno",
DROP COLUMN "isnegativeconsign",
DROP COLUMN "isovership",
DROP COLUMN "isprintshipbo",
DROP COLUMN "isprivilege",
DROP COLUMN "localiteid",
DROP COLUMN "login",
DROP COLUMN "methpaid",
DROP COLUMN "nameprop",
DROP COLUMN "noaccount",
DROP COLUMN "note",
DROP COLUMN "notebol",
DROP COLUMN "password",
DROP COLUMN "priceid",
DROP COLUMN "production",
DROP COLUMN "projectid",
DROP COLUMN "prospectstatus",
DROP COLUMN "regionid",
DROP COLUMN "sector",
DROP COLUMN "shipmentcontact",
DROP COLUMN "shipmentsendtype",
DROP COLUMN "siteid",
DROP COLUMN "srid",
DROP COLUMN "statementcontact",
DROP COLUMN "statementtype",
DROP COLUMN "status2",
DROP COLUMN "taxid",
DROP COLUMN "tel",
DROP COLUMN "tel2",
DROP COLUMN "tel3",
DROP COLUMN "tempcurrid",
DROP COLUMN "terrid",
DROP COLUMN "territory",
DROP COLUMN "transit",
DROP COLUMN "userid",
DROP COLUMN "vendid_acc",
DROP COLUMN "website",
ALTER COLUMN "CustCode" DROP NOT NULL,
ALTER COLUMN "CustCode" SET DATA TYPE TEXT,
ALTER COLUMN "Name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "public"."Items" DROP COLUMN "ActivityExcludedFromSchedule",
DROP COLUMN "ActivityExcludedFromTotal",
DROP COLUMN "ActivityForPurchase",
DROP COLUMN "AllowCumulateVacation",
DROP COLUMN "AllowPosPriceChangeAlways",
DROP COLUMN "BOMID",
DROP COLUMN "BatchQty",
DROP COLUMN "CustStock",
DROP COLUMN "DefaultLength",
DROP COLUMN "DefaultUnit",
DROP COLUMN "Discriminator",
DROP COLUMN "ExcludeInWip",
DROP COLUMN "ExpenseType",
DROP COLUMN "ExpiredDateRequired",
DROP COLUMN "GlTransferId",
DROP COLUMN "InternalTime",
DROP COLUMN "InternalTimeSales",
DROP COLUMN "IsAssemblyItem",
DROP COLUMN "IsDefaultBox",
DROP COLUMN "IsExcludeProfit",
DROP COLUMN "IsForRenting",
DROP COLUMN "IsForceReqQtyToSubAssembly",
DROP COLUMN "IsPrjOfficeActivity",
DROP COLUMN "IsShowEmergencyServiceCall",
DROP COLUMN "IsShowServiceCall",
DROP COLUMN "IsTaxableSalesOnly",
DROP COLUMN "IsWithTip",
DROP COLUMN "LastChange",
DROP COLUMN "Length",
DROP COLUMN "Mrpreq",
DROP COLUMN "NetWeight",
DROP COLUMN "NoTaxeOn",
DROP COLUMN "OrdPeriod",
DROP COLUMN "OrdPol",
DROP COLUMN "Ordqty",
DROP COLUMN "OtherInfo",
DROP COLUMN "Planorder",
DROP COLUMN "PrjEbdId",
DROP COLUMN "PrjFixAmount",
DROP COLUMN "PrjInvType",
DROP COLUMN "PrjIsDocumentMandatoryExpense",
DROP COLUMN "PrjIsFlatAmount",
DROP COLUMN "PrjIsHoliday",
DROP COLUMN "ProdId",
DROP COLUMN "RatePerKilometer",
DROP COLUMN "RatePerMile",
DROP COLUMN "ReorderQty",
DROP COLUMN "RoutingID",
DROP COLUMN "SafetyTime",
DROP COLUMN "Safetyqty",
DROP COLUMN "Schedulable",
DROP COLUMN "Schedule",
DROP COLUMN "SetupHours",
DROP COLUMN "ShipWeight",
DROP COLUMN "TimeFence",
DROP COLUMN "TypeMON",
DROP COLUMN "UomId",
DROP COLUMN "Vacation",
DROP COLUMN "Velocity",
DROP COLUMN "VendID",
DROP COLUMN "WcClassId",
DROP COLUMN "WebLanguageCodeDescr",
DROP COLUMN "WithReplacement",
DROP COLUMN "_StdCostSinto",
DROP COLUMN "_model",
DROP COLUMN "_tempExpertPrice",
DROP COLUMN "_tempStdCostSinto",
DROP COLUMN "abc",
DROP COLUMN "autowo",
DROP COLUMN "autowoonorder",
DROP COLUMN "billable",
DROP COLUMN "categoryinspect",
DROP COLUMN "cieid",
DROP COLUMN "copiedfromitemid",
DROP COLUMN "cost",
DROP COLUMN "costmethod",
DROP COLUMN "countryid",
DROP COLUMN "createdDate",
DROP COLUMN "defaultopid",
DROP COLUMN "defaultpricelistid",
DROP COLUMN "deptech",
DROP COLUMN "descrsoum",
DROP COLUMN "dimensiontypeid",
DROP COLUMN "diversshowdescr",
DROP COLUMN "drawing",
DROP COLUMN "equipmenttype",
DROP COLUMN "formattemp",
DROP COLUMN "fromitemmasterid",
DROP COLUMN "grpname",
DROP COLUMN "htsnumber",
DROP COLUMN "imagesolidworks",
DROP COLUMN "inspecmodificationdate",
DROP COLUMN "inspectpct",
DROP COLUMN "invuomid",
DROP COLUMN "isActive",
DROP COLUMN "isDivers",
DROP COLUMN "isQuotation",
DROP COLUMN "isSchedulable",
DROP COLUMN "isbtnperso2blue",
DROP COLUMN "isbtnpersoblue",
DROP COLUMN "isdimensionedpurchase",
DROP COLUMN "isdiscount",
DROP COLUMN "isexchangeable",
DROP COLUMN "isexcludeseperationcost",
DROP COLUMN "isextranet",
DROP COLUMN "isinposlist",
DROP COLUMN "isitemdispos",
DROP COLUMN "ismaster",
DROP COLUMN "ismultipleBT",
DROP COLUMN "isnotdisplaypage2",
DROP COLUMN "isnotdisplayreq",
DROP COLUMN "isnotinbox",
DROP COLUMN "isondiscount",
DROP COLUMN "ispayable",
DROP COLUMN "ispreventmaintenance",
DROP COLUMN "isproddate",
DROP COLUMN "isserialno",
DROP COLUMN "isserialnoqty",
DROP COLUMN "isshowinstallation",
DROP COLUMN "isspolicy",
DROP COLUMN "istaxable",
DROP COLUMN "istransitlocinexcluded",
DROP COLUMN "iswarranty",
DROP COLUMN "iswebvisible",
DROP COLUMN "iswobillable",
DROP COLUMN "iswomerge",
DROP COLUMN "itemgrpid",
DROP COLUMN "itemidMP",
DROP COLUMN "itemidorig",
DROP COLUMN "itempricedimension",
DROP COLUMN "itemsubtypeid",
DROP COLUMN "itemtype",
DROP COLUMN "lastUpdated",
DROP COLUMN "leadtime",
DROP COLUMN "locid",
DROP COLUMN "locitemtype",
DROP COLUMN "loguserid",
DROP COLUMN "masteritemid",
DROP COLUMN "maxqty",
DROP COLUMN "metadescr",
DROP COLUMN "metakeyword",
DROP COLUMN "metaname",
DROP COLUMN "minqty",
DROP COLUMN "model",
DROP COLUMN "multiplierqty",
DROP COLUMN "netuomid",
DROP COLUMN "newdescr",
DROP COLUMN "nomanufac",
DROP COLUMN "noteinspect",
DROP COLUMN "noteproduction",
DROP COLUMN "notepurchase",
DROP COLUMN "packagingitemid",
DROP COLUMN "phantom",
DROP COLUMN "pm_code",
DROP COLUMN "posexclude",
DROP COLUMN "posinvnote",
DROP COLUMN "price",
DROP COLUMN "publishdate",
DROP COLUMN "qtyBuffer",
DROP COLUMN "qtyalloc",
DROP COLUMN "qtyonhand",
DROP COLUMN "qtyonorder",
DROP COLUMN "qtyonpo",
DROP COLUMN "quoteprice",
DROP COLUMN "quoteuomid",
DROP COLUMN "rcptpercent",
DROP COLUMN "revdate",
DROP COLUMN "revision",
DROP COLUMN "salesnote",
DROP COLUMN "salesuomid",
DROP COLUMN "sequence",
DROP COLUMN "shipuomid",
DROP COLUMN "shopify",
DROP COLUMN "shopifyProductId",
DROP COLUMN "shoplineid",
DROP COLUMN "showdimension",
DROP COLUMN "siteid",
DROP COLUMN "specid",
DROP COLUMN "status",
DROP COLUMN "statusprod",
DROP COLUMN "styleid",
DROP COLUMN "submodel",
DROP COLUMN "taxesitemsid",
DROP COLUMN "temporaire",
DROP COLUMN "titledescr",
DROP COLUMN "uomalt1",
DROP COLUMN "uomalt2",
DROP COLUMN "uomalt3",
DROP COLUMN "uomfactor1",
DROP COLUMN "uomfactor2",
DROP COLUMN "uomfactor3",
DROP COLUMN "uomidsales",
DROP COLUMN "uomprice1",
DROP COLUMN "uomprice2",
DROP COLUMN "uomprice3",
DROP COLUMN "upccode",
DROP COLUMN "userid",
DROP COLUMN "volume",
DROP COLUMN "volumeuomid",
DROP COLUMN "wcid",
DROP COLUMN "webdescr",
DROP COLUMN "webname",
DROP COLUMN "withannexe",
DROP COLUMN "wofactor",
ALTER COLUMN "ItemCode" SET NOT NULL,
ALTER COLUMN "ItemCode" SET DATA TYPE TEXT,
ALTER COLUMN "Descr" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "public"."Locations" DROP COLUMN "CieId",
DROP COLUMN "LocCode",
DROP COLUMN "LocItemType",
DROP COLUMN "Permanent",
DROP COLUMN "SiteId",
DROP COLUMN "isactive",
DROP COLUMN "isdefault",
DROP COLUMN "quarantine",
DROP COLUMN "seq",
ALTER COLUMN "Name" SET NOT NULL,
ALTER COLUMN "Name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "public"."SOHeader" DROP COLUMN "AssistEmplId",
DROP COLUMN "BudgetAmt",
DROP COLUMN "CONTACT",
DROP COLUMN "Confirmed",
DROP COLUMN "CreditLimitAddedShipping",
DROP COLUMN "CurrId",
DROP COLUMN "CurrRate",
DROP COLUMN "CustomerContactId",
DROP COLUMN "Dateconfirmed",
DROP COLUMN "Discriminator",
DROP COLUMN "DueDate",
DROP COLUMN "FixedPrice",
DROP COLUMN "GLVerifyType1",
DROP COLUMN "HoldShippingAmount",
DROP COLUMN "InternalNote",
DROP COLUMN "Invnbrproforma",
DROP COLUMN "InvoiceTypeId",
DROP COLUMN "IsActive",
DROP COLUMN "IsExcludeTransfertGL",
DROP COLUMN "IsHold",
DROP COLUMN "IsProjectAtCost",
DROP COLUMN "Langid",
DROP COLUMN "LastModifiedDateStatus",
DROP COLUMN "PaymentMethodId",
DROP COLUMN "PoNbr",
DROP COLUMN "PrepareBy",
DROP COLUMN "PriceListId",
DROP COLUMN "PricingDate",
DROP COLUMN "PrjInactiveDate",
DROP COLUMN "PrjIsBillable",
DROP COLUMN "PrjIsFlatAmount",
DROP COLUMN "PrjPctCompleted",
DROP COLUMN "PrjUserId",
DROP COLUMN "ProdId",
DROP COLUMN "ProjectDescr",
DROP COLUMN "ProjectID",
DROP COLUMN "ProjectManager",
DROP COLUMN "ProjectNumber",
DROP COLUMN "ProjectType",
DROP COLUMN "PromiseDate",
DROP COLUMN "Reprice",
DROP COLUMN "SONbrBBL",
DROP COLUMN "SoldAmt",
DROP COLUMN "Tax3amt",
DROP COLUMN "TypetransInv",
DROP COLUMN "YearEnd",
DROP COLUMN "_ApprobationExpertCode",
DROP COLUMN "_ApprobationExpertReason",
DROP COLUMN "_CybercatDetailEvent",
DROP COLUMN "_CybercatEventCode",
DROP COLUMN "_CybercatMode",
DROP COLUMN "_CybercatPromiseDate",
DROP COLUMN "_DashIsNoCityConfig",
DROP COLUMN "_DashboardNote",
DROP COLUMN "_ExpertAdj",
DROP COLUMN "_TotalWeight",
DROP COLUMN "_apicarrid",
DROP COLUMN "_carrieraccountno",
DROP COLUMN "_cybercatTransno",
DROP COLUMN "_isimportedfromApi",
DROP COLUMN "approvedsubtotalamt",
DROP COLUMN "billcustid",
DROP COLUMN "billtoid",
DROP COLUMN "ciesectorid",
DROP COLUMN "commid",
DROP COLUMN "contactid",
DROP COLUMN "createddate",
DROP COLUMN "datesend",
DROP COLUMN "description",
DROP COLUMN "discountpercent",
DROP COLUMN "divisioncode",
DROP COLUMN "emplid",
DROP COLUMN "fob",
DROP COLUMN "freight",
DROP COLUMN "holdpercentforinv",
DROP COLUMN "holdreasoncode",
DROP COLUMN "holdtype",
DROP COLUMN "isfrompos",
DROP COLUMN "isholdShipping",
DROP COLUMN "isnewso",
DROP COLUMN "isrent",
DROP COLUMN "isshipReleased",
DROP COLUMN "istimebank",
DROP COLUMN "isvoid",
DROP COLUMN "itemserialid",
DROP COLUMN "linepricing",
DROP COLUMN "livraison",
DROP COLUMN "loguserid",
DROP COLUMN "nbhours",
DROP COLUMN "nofolder",
DROP COLUMN "othershipaddress",
DROP COLUMN "parentsoid",
DROP COLUMN "paymentduedate",
DROP COLUMN "projectName",
DROP COLUMN "qonbr",
DROP COLUMN "rate1amt",
DROP COLUMN "rate2amt",
DROP COLUMN "rate3amt",
DROP COLUMN "remark",
DROP COLUMN "shiptoid",
DROP COLUMN "shopifyOrderId",
DROP COLUMN "shopifyOrderPaid",
DROP COLUMN "siteid",
DROP COLUMN "soid",
DROP COLUMN "somainid",
DROP COLUMN "sotype",
DROP COLUMN "status",
DROP COLUMN "storeno",
DROP COLUMN "subtotalamt",
DROP COLUMN "targetsiteid",
DROP COLUMN "tax1amt",
DROP COLUMN "tax2amt",
DROP COLUMN "taxid",
DROP COLUMN "tempcurrid",
DROP COLUMN "termid",
DROP COLUMN "terrid",
ALTER COLUMN "OrderDate" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "public"."Salesrep" DROP COLUMN "AnonymizationInactiveDate",
DROP COLUMN "AnonymizationLogId",
DROP COLUMN "City",
DROP COLUMN "Countryid",
DROP COLUMN "IsActive",
DROP COLUMN "Langid",
DROP COLUMN "Line1",
DROP COLUMN "Line2",
DROP COLUMN "SRCode",
DROP COLUMN "Stateid",
DROP COLUMN "ZipCode",
DROP COLUMN "_securityDeposit",
DROP COLUMN "cieid",
DROP COLUMN "ciesectorid",
DROP COLUMN "commid",
DROP COLUMN "geoLocation",
DROP COLUMN "posdeviceid",
DROP COLUMN "regionid",
DROP COLUMN "siteid",
DROP COLUMN "tel",
DROP COLUMN "title",
DROP COLUMN "userid",
DROP COLUMN "vendid",
ALTER COLUMN "Name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "public"."ShipmentHdr" DROP COLUMN "Confirmed",
DROP COLUMN "CustId",
DROP COLUMN "FreightCost",
DROP COLUMN "FromSiteId",
DROP COLUMN "InternalNote",
DROP COLUMN "IsMultiSo",
DROP COLUMN "ReceiptDate",
DROP COLUMN "ShipmentType",
DROP COLUMN "ShopifyFulfillmentid",
DROP COLUMN "SignatureName",
DROP COLUMN "SignaturePath",
DROP COLUMN "TargetSiteId",
DROP COLUMN "_CreationDate",
DROP COLUMN "_DashDetailLine2",
DROP COLUMN "_DashNote",
DROP COLUMN "_DashPalletDim",
DROP COLUMN "_DashPalletNbr",
DROP COLUMN "_DashSendType",
DROP COLUMN "_DashShippingChargeCode",
DROP COLUMN "_DashTailgate",
DROP COLUMN "_IsDashboardBo",
DROP COLUMN "_IsPrinted",
DROP COLUMN "_IsReadyForInvoicing",
DROP COLUMN "_WayBillSentToCarrier",
DROP COLUMN "_sendingunit",
DROP COLUMN "bolid",
DROP COLUMN "boxtype",
DROP COLUMN "carrid",
DROP COLUMN "contact",
DROP COLUMN "dateclose",
DROP COLUMN "datesend",
DROP COLUMN "fob",
DROP COLUMN "freightapinvoiceid",
DROP COLUMN "invnbr",
DROP COLUMN "isactive",
DROP COLUMN "isshipped",
DROP COLUMN "isvoid",
DROP COLUMN "nbrbox",
DROP COLUMN "notes",
DROP COLUMN "othershipaddress",
DROP COLUMN "shipdate",
DROP COLUMN "shipmentnbr",
DROP COLUMN "shippingnote",
DROP COLUMN "shiptoid",
DROP COLUMN "shopifyTrackingNumber",
DROP COLUMN "somainid",
DROP COLUMN "totalbox",
DROP COLUMN "userid",
ALTER COLUMN "sonbr" SET NOT NULL,
ALTER COLUMN "WayBill" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "public"."Sites" DROP COLUMN "AnonymizationInactiveDate",
DROP COLUMN "AnonymizationLogId",
DROP COLUMN "CieId",
DROP COLUMN "CommissionFixed",
DROP COLUMN "CommissionRate",
DROP COLUMN "EDIIdentifier",
DROP COLUMN "SiteCode",
DROP COLUMN "_isSintoSite",
DROP COLUMN "affiliatedsiteid",
DROP COLUMN "allusers",
DROP COLUMN "city",
DROP COLUMN "countryid",
DROP COLUMN "dropaddrid",
DROP COLUMN "fax",
DROP COLUMN "geoLocation",
DROP COLUMN "isactive",
DROP COLUMN "isdefault",
DROP COLUMN "issubcontract",
DROP COLUMN "issyncinvoices",
DROP COLUMN "issyncitems",
DROP COLUMN "issyncitemsdoc",
DROP COLUMN "issyncitemsdocPDF",
DROP COLUMN "issyncmeta",
DROP COLUMN "issyncorders",
DROP COLUMN "issyncshipments",
DROP COLUMN "line1",
DROP COLUMN "line2",
DROP COLUMN "palletlocid",
DROP COLUMN "phone",
DROP COLUMN "roadid",
DROP COLUMN "shopifyAPIKey",
DROP COLUMN "shopifyAccessToken",
DROP COLUMN "shopifyCustId",
DROP COLUMN "shopifyPriceId",
DROP COLUMN "shopifyStoreUrl",
DROP COLUMN "stateid",
DROP COLUMN "zipcode",
ALTER COLUMN "Name" SET NOT NULL,
ALTER COLUMN "Name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "public"."carriers" DROP COLUMN "AnonymizationInactiveDate",
DROP COLUMN "AnonymizationLogId",
DROP COLUMN "Cieid",
DROP COLUMN "DutyBrokerId",
DROP COLUMN "RIN",
DROP COLUMN "WayBillCode",
DROP COLUMN "accountno",
DROP COLUMN "adress",
DROP COLUMN "apicarrierid",
DROP COLUMN "apicarrierserviceid",
DROP COLUMN "carrcode",
DROP COLUMN "city",
DROP COLUMN "country",
DROP COLUMN "currid",
DROP COLUMN "email",
DROP COLUMN "fax",
DROP COLUMN "fuelsurcharge",
DROP COLUMN "isactive",
DROP COLUMN "phone",
DROP COLUMN "scaccode",
DROP COLUMN "state",
DROP COLUMN "vendid",
DROP COLUMN "zipcode",
ALTER COLUMN "name" SET NOT NULL,
ALTER COLUMN "name" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "public"."itemsite" DROP COLUMN "_backupqtyonhand",
DROP COLUMN "batchqty",
DROP COLUMN "locdefault",
DROP COLUMN "locposition",
DROP COLUMN "maxqty",
DROP COLUMN "minqty",
DROP COLUMN "qtyalloc",
DROP COLUMN "qtyonorder",
DROP COLUMN "qtyonpo",
DROP COLUMN "rankno",
ALTER COLUMN "qtyonhand" DROP NOT NULL,
ALTER COLUMN "cieid" DROP NOT NULL,
ALTER COLUMN "locid" DROP NOT NULL;

-- AlterTable
ALTER TABLE "public"."sharepoint_nodes" DROP COLUMN "permissions",
ALTER COLUMN "type" SET NOT NULL,
ALTER COLUMN "type" SET DEFAULT 'folder',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updatedAt" DROP DEFAULT,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(3);

-- DropTable
DROP TABLE "public"."InvDetail";

-- DropTable
DROP TABLE "public"."InvHeader";

-- DropTable
DROP TABLE "public"."PODetail";

-- DropTable
DROP TABLE "public"."POHeader";

-- DropTable
DROP TABLE "public"."WODetail";

-- DropTable
DROP TABLE "public"."itempricelist";

-- DropTable
DROP TABLE "public"."itemscost";

-- DropTable
DROP TABLE "public"."territories";

-- DropTable
DROP TABLE "public"."wohdr";

-- CreateTable
CREATE TABLE "public"."returns" (
    "id" SERIAL NOT NULL,
    "code" TEXT NOT NULL,
    "reportedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reporter" "public"."Reporter" NOT NULL,
    "cause" "public"."Cause" NOT NULL,
    "expert" TEXT NOT NULL,
    "client" TEXT NOT NULL,
    "noClient" TEXT,
    "noCommande" TEXT,
    "tracking" TEXT,
    "status" "public"."ReturnStatus" NOT NULL DEFAULT 'draft',
    "standby" BOOLEAN NOT NULL DEFAULT false,
    "amount" DECIMAL(12,2),
    "dateCommande" TIMESTAMP(3),
    "transport" TEXT,
    "description" TEXT,
    "createdByName" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "returns_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."return_products" (
    "id" SERIAL NOT NULL,
    "returnId" INTEGER NOT NULL,
    "codeProduit" TEXT NOT NULL,
    "descriptionProduit" TEXT NOT NULL,
    "descriptionRetour" TEXT,
    "quantite" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "return_products_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."uploads" (
    "id" SERIAL NOT NULL,
    "returnId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "uploads_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "returns_code_key" ON "public"."returns"("code");

-- CreateIndex
CREATE INDEX "returns_reportedAt_idx" ON "public"."returns"("reportedAt");

-- CreateIndex
CREATE INDEX "returns_status_idx" ON "public"."returns"("status");

-- CreateIndex
CREATE INDEX "returns_noCommande_idx" ON "public"."returns"("noCommande");

-- CreateIndex
CREATE INDEX "return_products_returnId_idx" ON "public"."return_products"("returnId");

-- CreateIndex
CREATE INDEX "return_products_codeProduit_idx" ON "public"."return_products"("codeProduit");

-- CreateIndex
CREATE INDEX "uploads_returnId_idx" ON "public"."uploads"("returnId");

-- CreateIndex
CREATE INDEX "Items_ItemCode_idx" ON "public"."Items"("ItemCode");

-- CreateIndex
CREATE INDEX "ShipmentHdr_sonbr_idx" ON "public"."ShipmentHdr"("sonbr");

-- CreateIndex
CREATE INDEX "itemsite_itemid_siteid_idx" ON "public"."itemsite"("itemid", "siteid");

-- AddForeignKey
ALTER TABLE "public"."return_products" ADD CONSTRAINT "return_products_returnId_fkey" FOREIGN KEY ("returnId") REFERENCES "public"."returns"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."uploads" ADD CONSTRAINT "uploads_returnId_fkey" FOREIGN KEY ("returnId") REFERENCES "public"."returns"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- RenameIndex
ALTER INDEX "public"."idx_spn_tenant" RENAME TO "sharepoint_nodes_tenantId_idx";

-- RenameIndex
ALTER INDEX "public"."idx_spn_tenant_parent" RENAME TO "sharepoint_nodes_tenantId_parentId_idx";

