version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ca-central-1"
    AWS_ACCOUNT_ID: "586359898361"
    IMAGE_REPO_NAME: "nartex-next"

    # App env you pass into the Docker build (if your Dockerfile uses them)
    NEXTAUTH_URL: "https://app.nartex.ca"
    EMAIL_SERVER_HOST: "smtp.gmail.com"
    EMAIL_SERVER_PORT: "587"
    EMAIL_SERVER_USER: "n.labranche@nartex.ca"
    EMAIL_FROM: "Nartex <noreply@nartex.ca>"
    AZURE_AD_TENANT_ID: "organizations"

    # ECS targets (adjust to your real names)
    CLUSTER_NAME: "nartex-cluster"
    SERVICE_NAME: "nartex-next-service"

  secrets-manager:
    DATABASE_URL:           nartex/prod/env:DATABASE_URL
    EMAIL_SERVER_PASSWORD:  nartex/prod/env:EMAIL_SERVER_PASSWORD
    NEXTAUTH_SECRET:        nartex/prod/env:NEXTAUTH_SECRET
    GOOGLE_CLIENT_ID:       nartex/prod/env:GOOGLE_CLIENT_ID
    GOOGLE_CLIENT_SECRET:   nartex/prod/env:GOOGLE_CLIENT_SECRET
    AZURE_AD_CLIENT_ID:     nartex/prod/env:AZURE_AD_CLIENT_ID
    AZURE_AD_CLIENT_SECRET: nartex/prod/env:AZURE_AD_CLIENT_SECRET
    RDS_CREDENTIALS:        nartex/prod/rds-credentials

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "📦 INSTALL – npm ci for build tooling"
      - npm ci

  pre_build:
    commands:
      - echo "📜 PRE_BUILD – write script to disk and run it"
      - |
        cat > ci-prebuild.sh << 'SH'
        #!/usr/bin/env bash
        set -euo pipefail
        set -x

        # Forcefully remove the old, incorrect auth file to prevent build conflicts.
        echo "Removing legacy auth file at src/lib/auth.ts to prevent build conflicts..."
        rm -f src/lib/auth.ts

        # 1) Runtime deps
        npm pkg set dependencies.recharts="^2.12.7"
        npm pkg set dependencies.lucide-react="^0.452.0"
        npm pkg set dependencies.class-variance-authority="^0.7.0"
        npm pkg set dependencies.clsx="^2.1.1"
        npm pkg set dependencies.tailwind-merge="^2.5.2"
        npm pkg set dependencies.tailwindcss-animate="^1.0.7"
        npm pkg set dependencies.pg="^8.11.3"
        npm pkg set dependencies.swr="^2.3.0"
        npm pkg set dependencies.@next-auth/prisma-adapter="^1.0.7"

        # 1b) Dev typings so TS is happy in CI
        npm pkg set devDependencies.@types/node="^18.19.0"
        npm pkg set devDependencies.@types/pg="^8.11.7"

        # 2) shadcn config (idempotent)
        node <<'NODE'
        const fs = require('fs');
        const p = 'components.json';
        const j = fs.existsSync(p) ? JSON.parse(fs.readFileSync(p,'utf8')) : {};
        j.$schema = 'https://ui.shadcn.com/schema.json';
        j.style = 'default';
        j.rsc = true;
        j.tsx = true;
        j.tailwind = { config: 'tailwind.config.ts', css: 'src/app/globals.css', baseColor: 'gray', cssVariables: true };
        j.aliases = { components: '@/components', utils: '@/lib/utils' };
        j.iconLibrary = 'lucide';
        j.components = j.components || [];
        j.path = 'src/components';
        fs.writeFileSync(p, JSON.stringify(j, null, 2));
        NODE

        mkdir -p src/lib src/components/ui src/components/dashboard

        # 3) cn() helper if missing
        if [ ! -f src/lib/utils.ts ]; then
          cat > src/lib/utils.ts << 'TS'
        import type { ClassValue } from "clsx";
        import clsx from "clsx";
        import { twMerge } from "tailwind-merge";
        export function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)); }
        TS
        fi

        # 5) Minimal stubs so Next build doesn't break if these are missing
        if [ ! -f src/components/nartex-logo.tsx ]; then
          cat > src/components/nartex-logo.tsx << 'TSX'
        import * as React from "react";
        export default function NartexLogo({ className="" }: { className?: string }) {
          return <span className={className} style={{ fontWeight: 600, letterSpacing: ".05em" }}>nartex</span>;
        }
        TSX
        fi

        if [ ! -f src/components/dashboard/header.tsx ]; then
          cat > src/components/dashboard/header.tsx << 'TSX'
        export default function DashboardHeader(){ return <div className="px-4 py-3 text-sm text-muted-foreground">Dashboard Header</div>; }
        TSX
        fi

        if [ ! -f src/components/dashboard/sidebar.tsx ]; then
          cat > src/components/dashboard/sidebar.tsx << 'TSX'
        export default function DashboardSidebar(){ return <aside className="p-4 text-sm text-muted-foreground">Sidebar</aside>; }
        TSX
        fi

        if [ ! -f src/components/dashboard/new-product-requests-table.tsx ]; then
          cat > src/components/dashboard/new-product-requests-table.tsx << 'TSX'
        export default function NewProductRequestsTable(){ return <div className="p-4 text-sm text-muted-foreground">New product requests (stub)</div>; }
        TSX
        fi

        if [ ! -f src/components/product-requests-table.tsx ]; then
          cat > src/components/product-requests-table.tsx << 'TSX'
        export default function ProductRequestsTable(){ return <div className="p-4 text-sm text-muted-foreground">Product requests (stub)</div>; }
        TSX
        fi

        echo "📂 Components present:"; ls -la src/components || true; ls -la src/components/dashboard || true

        # 6) Refresh lockfile for Docker layer cache
        npm install --package-lock-only --ignore-scripts --no-audit --no-fund
        SH
      - chmod +x ci-prebuild.sh
      - bash ci-prebuild.sh

  build:
    commands:
      - echo "🏗 BUILD – docker image $ECR_IMAGE_URI:$COMMIT_HASH"
      - |
        docker build \
          --build-arg GIT_COMMIT_HASH="$COMMIT_HASH" \
          --build-arg DATABASE_URL="$DATABASE_URL" \
          --build-arg EMAIL_SERVER_HOST="$EMAIL_SERVER_HOST" \
          --build-arg EMAIL_SERVER_PORT="$EMAIL_SERVER_PORT" \
          --build-arg EMAIL_SERVER_USER="$EMAIL_SERVER_USER" \
          --build-arg EMAIL_SERVER_PASSWORD="$EMAIL_SERVER_PASSWORD" \
          --build-arg EMAIL_FROM="$EMAIL_FROM" \
          --build-arg NEXTAUTH_URL="$NEXTAUTH_URL" \
          --build-arg NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
          --build-arg GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
          --build-arg GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" \
          --build-arg AZURE_AD_CLIENT_ID="$AZURE_AD_CLIENT_ID" \
          --build-arg AZURE_AD_CLIENT_SECRET="$AZURE_AD_CLIENT_SECRET" \
          --build-arg AZURE_AD_TENANT_ID="$AZURE_AD_TENANT_ID" \
          -t "$ECR_IMAGE_URI:$COMMIT_HASH" \
          -t "$ECR_IMAGE_URI:latest" .

      - echo "📤 Push images"
      - docker push "$ECR_IMAGE_URI:$COMMIT_HASH"
      - docker push "$ECR_IMAGE_URI:latest"

  post_build:
    commands:
      - echo "🔄 Force new ECS deployment (CodeBuild-only)"
      - |
        aws ecs update-service \
          --cluster "$CLUSTER_NAME" \
          --service "$SERVICE_NAME" \
          --force-new-deployment \
          --region "$AWS_DEFAULT_REGION"

        echo "⏳ Waiting for service to stabilize…"
        aws ecs wait services-stable \
          --cluster "$CLUSTER_NAME" \
          --services "$SERVICE_NAME" \
          --region "$AWS_DEFAULT_REGION"

      - echo "✅ ECS deployment complete."

# No artifacts needed when deploying directly from CodeBuild
artifacts:
  files:
    - .git/HEAD
