version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: nartex-next        # quotes not required here
  secrets-manager:
    DATABASE_URL: nartex-db-credentials

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - 'echo "Phase: install – Installing project dependencies..."'
      - npm ci

  pre_build:
  commands:
    - echo "Logging in to Amazon ECR..."
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION \
      | docker login --username AWS --password-stdin \
      $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - which docker && docker --version
    - docker info | head -5

  build:
    commands:
      - 'echo "Phase: build – Getting Git commit hash..."'
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - 'echo "Building Docker image with tags $COMMIT_HASH and latest"'
      - ECR_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - docker build -t $ECR_IMAGE_URI:$COMMIT_HASH .
      - docker tag $ECR_IMAGE_URI:$COMMIT_HASH $ECR_IMAGE_URI:latest
      - echo "Pushing image tagged $COMMIT_HASH to ECR..."
      - docker push $ECR_IMAGE_URI:$COMMIT_HASH
      - echo "Pushing image tagged latest to ECR..."
      - docker push $ECR_IMAGE_URI:latest

  post_build:
    commands:
      - 'echo "Phase: post_build – Creating image definitions file..."'
      - printf '[{"name":"nextjs","imageUri":"%s"}]' \
          "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_HASH" \
          > imagedefinitions.json
      - 'echo "Generated imagedefinitions.json:"'
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
