version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "586359898361"
    IMAGE_REPO_NAME: "nartex-next"
    NEXTAUTH_URL: "https://app.nartex.ca"
    EMAIL_SERVER_HOST: "smtp.gmail.com"
    EMAIL_SERVER_PORT: "587"
    EMAIL_SERVER_USER: "n.labranche@nartex.ca"
    EMAIL_FROM: "Nartex <noreply@nartex.ca>"
    AZURE_AD_TENANT_ID: "organizations"

  secrets-manager:
    EMAIL_SERVER_PASSWORD:  nartex/prod/env:EMAIL_SERVER_PASSWORD
    NEXTAUTH_SECRET:        nartex/prod/env:NEXTAUTH_SECRET
    GOOGLE_CLIENT_ID:       nartex/prod/env:GOOGLE_CLIENT_ID
    GOOGLE_CLIENT_SECRET:   nartex/prod/env:GOOGLE_CLIENT_SECRET
    AZURE_AD_CLIENT_ID:     nartex/prod/env:AZURE_AD_CLIENT_ID
    AZURE_AD_CLIENT_SECRET: nartex/prod/env:AZURE_AD_CLIENT_SECRET
    RDS_CREDENTIALS:        nartex/prod/rds-credentials
    # If you still want to pass a direct connection string during build, uncomment:
    # DATABASE_URL:           nartex/prod/env:DATABASE_URL

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "📦 INSTALL – npm ci for workspace tooling"
      - npm ci

  pre_build:
    commands:
      - echo "📜 PRE_BUILD – write script to disk and run it"
      - |
        cat > ci-prebuild.sh << 'SH'
        #!/usr/bin/env bash
        set -euo pipefail
        set -x

        # 1) Ensure runtime deps used by dashboard
        npm pkg set dependencies.recharts="^2.12.7"
        npm pkg set dependencies.lucide-react="^0.452.0"
        npm pkg set dependencies.class-variance-authority="^0.7.0"
        npm pkg set dependencies.clsx="^2.1.1"
        npm pkg set dependencies.tailwind-merge="^2.5.2"
        npm pkg set dependencies.tailwindcss-animate="^1.0.7"
        npm pkg set dependencies.pg="^8.11.3"       # PostgreSQL client
        npm pkg set dependencies.swr="^2.3.0"       # SWR used by /app/dashboard

        # 2) Ensure shadcn writes into src/components and aliases match @/*
        node <<'NODE'
        const fs = require('fs');
        const p = 'components.json';
        const j = fs.existsSync(p) ? JSON.parse(fs.readFileSync(p,'utf8')) : {};
        j.$schema = 'https://ui.shadcn.com/schema.json';
        j.style = 'default';
        j.rsc = true;
        j.tsx = true;
        j.tailwind = { config: 'tailwind.config.ts', css: 'src/app/globals.css', baseColor: 'gray', cssVariables: true };
        j.aliases = { components: '@/components', utils: '@/lib/utils' };
        j.iconLibrary = 'lucide';
        j.components = j.components || [];
        j.path = 'src/components';
        fs.writeFileSync(p, JSON.stringify(j, null, 2));
        NODE

        mkdir -p src/lib src/components/ui

        # 3) cn() helper
        if [ ! -f src/lib/utils.ts ]; then
          cat > src/lib/utils.ts << 'TS'
        import { type ClassValue } from "clsx";
        import clsx from "clsx";
        import { twMerge } from "tailwind-merge";
        export function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)); }
        TS
        fi

        # 4) shadcn init (won't fail build if it complains)
        npx --yes shadcn@latest init -d || true

        # 5) Add components if missing (ignore errors)
        add_if_missing () {
          local NAME="$1"
          if [ ! -f "src/components/ui/${NAME}.tsx" ] && [ ! -f "src/components/ui/${NAME}.ts" ]; then
            echo "Adding $NAME"
            npx --yes shadcn@latest add "$NAME" || true
          else
            echo "Skipping $NAME (already exists)"
          fi
        }
        for c in button card table tabs input select badge; do add_if_missing "$c"; done

        # 6) Minimal fallbacks (only if still missing)
        if [ ! -f src/components/ui/input.tsx ]; then
          cat > src/components/ui/input.tsx << 'TSX'
        import * as React from "react";
        import { cn } from "@/lib/utils";
        export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {}
        export const Input = React.forwardRef<HTMLInputElement, InputProps>(
          ({ className, ...props }, ref) => (
            <input ref={ref} className={cn("flex h-9 w-full rounded-md border bg-background px-3 py-2 text-sm outline-none", className)} {...props} />
          )
        ); Input.displayName="Input"; export default Input;
        TSX
        fi

        if [ ! -f src/components/ui/button.tsx ]; then
          cat > src/components/ui/button.tsx << 'TSX'
        import * as React from "react";
        import { cn } from "@/lib/utils";
        export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {}
        export function Button({ className, ...props }: ButtonProps) {
          return <button className={cn("inline-flex h-9 items-center rounded-md border px-3 text-sm", className)} {...props} />;
        }
        export default Button;
        TSX
        fi

        if [ ! -f src/components/ui/card.tsx ]; then
          cat > src/components/ui/card.tsx << 'TSX'
        import * as React from "react";
        import { cn } from "@/lib/utils";
        export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
          return <div className={cn("rounded-xl border bg-card text-card-foreground shadow", className)} {...props} />;
        }
        export function CardHeader(props: React.HTMLAttributes<HTMLDivElement>) { return <div className="p-6" {...props} />; }
        export function CardContent(props: React.HTMLAttributes<HTMLDivElement>) { return <div className="p-6 pt-0" {...props} />; }
        export function CardTitle({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) { return <h3 className={cn("font-semibold", className)} {...props} />; }
        TSX
        fi

        if [ ! -f src/components/ui/table.tsx ]; then
          cat > src/components/ui/table.tsx << 'TSX'
        import * as React from "react";
        export const Table = (p: React.HTMLAttributes<HTMLTableElement>) => <table className="w-full text-sm" {...p} />;
        export const TableHeader = (p: React.HTMLAttributes<HTMLTableSectionElement>) => <thead {...p} />;
        export const TableBody = (p: React.HTMLAttributes<HTMLTableSectionElement>) => <tbody {...p} />;
        export const TableRow = (p: React.HTMLAttributes<HTMLTableRowElement>) => <tr className="border-b" {...p} />;
        export const TableHead = (p: React.ThHTMLAttributes<HTMLTableCellElement>) => <th className="text-left py-2 px-3" {...p} />;
        export const TableCell = (p: React.TdHTMLAttributes<HTMLTableCellElement>) => <td className="py-2 px-3" {...p} />;
        TSX
        fi

        if [ ! -f src/components/ui/tabs.tsx ]; then
          cat > src/components/ui/tabs.tsx << 'TSX'
        import * as React from "react";
        type TabsCtx = { value: string; set: (v: string)=>void };
        const Ctx = React.createContext<TabsCtx | null>(null);
        export function Tabs({ defaultValue, children }: { defaultValue: string; children: React.ReactNode }) {
          const [value, set] = React.useState(defaultValue);
          return <Ctx.Provider value={{ value, set }}>{children}</Ctx.Provider>;
        }
        export const TabsList = ({ children }: { children: React.ReactNode }) => <div className="flex gap-2">{children}</div>;
        export const TabsTrigger = ({ value, children }: { value: string; children: React.ReactNode }) => {
          const ctx = React.useContext(Ctx)!; const active = ctx.value === value;
          return <button onClick={() => ctx.set(value)} className={active ? "font-semibold" : ""}>{children}</button>;
        };
        export const TabsContent = ({ value, children }: { value: string; children: React.ReactNode }) => {
          const ctx = React.useContext(Ctx)!; return ctx.value === value ? <div>{children}</div> : null;
        };
        TSX
        fi

        if [ ! -f src/components/ui/select.tsx ]; then
          cat > src/components/ui/select.tsx << 'TSX'
        import * as React from "react";
        import { cn } from "@/lib/utils";
        export function Select({ value, onValueChange, children }:{ value?:string; onValueChange?:(v:string)=>void; children:React.ReactNode }) {
          return <div data-value={value}>{children}</div>;
        }
        export const SelectTrigger = ({ className, ...p }: React.HTMLAttributes<HTMLButtonElement>) => <button className={cn("h-9 rounded-md border px-3 text-sm", className)} {...p} />;
        export const SelectValue = ({ placeholder }: { placeholder?: string }) => <span>{placeholder}</span>;
        export const SelectContent = (p: React.HTMLAttributes<HTMLDivElement>) => <div className="mt-2 rounded-md border bg-background p-1" {...p} />;
        export const SelectItem = ({ value, children, onClick }: { value: string; children: React.ReactNode; onClick?: () => void }) =>
          <div onClick={onClick} data-value={value} className="cursor-pointer rounded px-2 py-1 hover:bg-muted">{children}</div>;
        TSX
        fi

        if [ ! -f src/components/ui/badge.tsx ]; then
          cat > src/components/ui/badge.tsx << 'TSX'
        import * as React from "react";
        export function Badge({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center rounded-md border px-2 py-0.5 text-xs">{children}</span>; }
        export default Badge;
        TSX
        fi

        echo "📂 Components present:"
        ls -la src/components/ui || true

        # 7) Refresh lockfile (Docker will npm ci from this)
        npm install --package-lock-only --ignore-scripts --no-audit --no-fund
        SH
      - chmod +x ci-prebuild.sh
      - bash ci-prebuild.sh

  build:
    commands:
      - echo "🏗 BUILD – resolve commit hash"
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - echo "🏗 BUILD – docker image (no cache)"
      - ECR_IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - |
        docker build \
          --no-cache \
          --build-arg GIT_COMMIT_HASH=$COMMIT_HASH \
          --build-arg DATABASE_URL="$DATABASE_URL" \
          --build-arg EMAIL_SERVER_HOST="$EMAIL_SERVER_HOST" \
          --build-arg EMAIL_SERVER_PORT="$EMAIL_SERVER_PORT" \
          --build-arg EMAIL_SERVER_USER="$EMAIL_SERVER_USER" \
          --build-arg EMAIL_SERVER_PASSWORD="$EMAIL_SERVER_PASSWORD" \
          --build-arg EMAIL_FROM="$EMAIL_FROM" \
          --build-arg NEXTAUTH_URL="$NEXTAUTH_URL" \
          --build-arg NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
          --build-arg GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
          --build-arg GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" \
          --build-arg AZURE_AD_CLIENT_ID="$AZURE_AD_CLIENT_ID" \
          --build-arg AZURE_AD_CLIENT_SECRET="$AZURE_AD_CLIENT_SECRET" \
          --build-arg AZURE_AD_TENANT_ID="$AZURE_AD_TENANT_ID" \
          -t "$ECR_IMAGE_URI:$COMMIT_HASH" \
          -t "$ECR_IMAGE_URI:latest" .

      - echo "🔑 Login to ECR"
      - |
        PASS="$(aws ecr get-login-password --region "$AWS_DEFAULT_REGION")"
        echo "$PASS" | docker login --username AWS --password-stdin "$ECR_IMAGE_URI"

      - echo "📤 Push images"
      - docker push "$ECR_IMAGE_URI:$COMMIT_HASH"
      - docker push "$ECR_IMAGE_URI:latest"

  post_build:
    commands:
      - echo "🔄 Force new ECS deployment"
      - |
        aws ecs update-service \
          --cluster nartex-cluster \
          --service nartex-next-service \
          --force-new-deployment \
          --region $AWS_DEFAULT_REGION
        # Tip: for bullet-proof rollouts, update task def to the exact $COMMIT_HASH tag.

artifacts:
  files:
    - imagedefinitions.json
