version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ca-central-1"
    AWS_ACCOUNT_ID: "586359898361"
    IMAGE_REPO_NAME: "nartex-next"

    # App env you pass into the Docker build (if your Dockerfile uses them)
    NEXTAUTH_URL: "https://app.nartex.ca"
    EMAIL_SERVER_HOST: "smtp.gmail.com"
    EMAIL_SERVER_PORT: "587"
    EMAIL_SERVER_USER: "n.labranche@nartex.ca"
    EMAIL_FROM: "Nartex <noreply@nartex.ca>"
    AZURE_AD_TENANT_ID: "organizations"

    # ECS targets (adjust to your real names)
    CLUSTER_NAME: "nartex-cluster"
    SERVICE_NAME: "nartex-next-service"

  secrets-manager:
    DATABASE_URL:           nartex/prod/env:DATABASE_URL
    EMAIL_SERVER_PASSWORD:  nartex/prod/env:EMAIL_SERVER_PASSWORD
    NEXTAUTH_SECRET:        nartex/prod/env:NEXTAUTH_SECRET
    GOOGLE_CLIENT_ID:       nartex/prod/env:GOOGLE_CLIENT_ID
    GOOGLE_CLIENT_SECRET:   nartex/prod/env:GOOGLE_CLIENT_SECRET
    AZURE_AD_CLIENT_ID:     nartex/prod/env:AZURE_AD_CLIENT_ID
    AZURE_AD_CLIENT_SECRET: nartex/prod/env:AZURE_AD_CLIENT_SECRET
    RDS_CREDENTIALS:        nartex/prod/rds-credentials

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "📦 INSTALL – npm ci for build tooling"
      - npm ci

  pre_build:
    commands:
      - echo "📜 PRE_BUILD – compute tags and login to ECR"
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - ECR_IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_IMAGE_URI"

  build:
    commands:
      - echo "🏗 BUILD – docker image $ECR_IMAGE_URI:$COMMIT_HASH"
      - |
        docker build \
          --build-arg GIT_COMMIT_HASH="$COMMIT_HASH" \
          --build-arg DATABASE_URL="$DATABASE_URL" \
          --build-arg EMAIL_SERVER_HOST="$EMAIL_SERVER_HOST" \
          --build-arg EMAIL_SERVER_PORT="$EMAIL_SERVER_PORT" \
          --build-arg EMAIL_SERVER_USER="$EMAIL_SERVER_USER" \
          --build-arg EMAIL_SERVER_PASSWORD="$EMAIL_SERVER_PASSWORD" \
          --build-arg EMAIL_FROM="$EMAIL_FROM" \
          --build-arg NEXTAUTH_URL="$NEXTAUTH_URL" \
          --build-arg NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
          --build-arg GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
          --build-arg GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" \
          --build-arg AZURE_AD_CLIENT_ID="$AZURE_AD_CLIENT_ID" \
          --build-arg AZURE_AD_CLIENT_SECRET="$AZURE_AD_CLIENT_SECRET" \
          --build-arg AZURE_AD_TENANT_ID="$AZURE_AD_TENANT_ID" \
          -t "$ECR_IMAGE_URI:$COMMIT_HASH" \
          -t "$ECR_IMAGE_URI:latest" .

      - echo "📤 Push images"
      - docker push "$ECR_IMAGE_URI:$COMMIT_HASH"
      - docker push "$ECR_IMAGE_URI:latest"

  post_build:
    commands:
      - echo "🔄 Force new ECS deployment (CodeBuild-only)"
      - |
        aws ecs update-service \
          --cluster "$CLUSTER_NAME" \
          --service "$SERVICE_NAME" \
          --force-new-deployment \
          --region "$AWS_DEFAULT_REGION"

        echo "⏳ Waiting for service to stabilize…"
        aws ecs wait services-stable \
          --cluster "$CLUSTER_NAME" \
          --services "$SERVICE_NAME" \
          --region "$AWS_DEFAULT_REGION"

      - echo "✅ ECS deployment complete."

# No artifacts needed when deploying directly from CodeBuild
artifacts:
  files:
    - .git/HEAD
