version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ca-central-1"
    AWS_ACCOUNT_ID: "586359898361"
    IMAGE_REPO_NAME: "nartex-next"
    CONTAINER_NAME: "nextjs"
    NEXTAUTH_URL: "https://app.nartex.ca"
    EMAIL_SERVER_HOST: "smtp.gmail.com"
    EMAIL_SERVER_PORT: "587"
    EMAIL_SERVER_USER: "n.labranche@nartex.ca"
    EMAIL_FROM: "Nartex <noreply@nartex.ca>"
    AZURE_AD_TENANT_ID: "organizations"

  secrets-manager:
    DATABASE_URL:           nartex/prod/env:DATABASE_URL
    EMAIL_SERVER_PASSWORD:  nartex/prod/env:EMAIL_SERVER_PASSWORD
    NEXTAUTH_SECRET:        nartex/prod/env:NEXTAUTH_SECRET
    GOOGLE_CLIENT_ID:       nartex/prod/env:GOOGLE_CLIENT_ID
    GOOGLE_CLIENT_SECRET:   nartex/prod/env:GOOGLE_CLIENT_SECRET
    AZURE_AD_CLIENT_ID:     nartex/prod/env:AZURE_AD_CLIENT_ID
    AZURE_AD_CLIENT_SECRET: nartex/prod/env:AZURE_AD_CLIENT_SECRET
    RDS_CREDENTIALS:        nartex/prod/rds-credentials
    DOCKERHUB_USERNAME:     dockerhub/credentials:DOCKERHUB_USERNAME
    DOCKERHUB_PASSWORD:     dockerhub/credentials:DOCKERHUB_PASSWORD

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "INSTALL: Installing dependencies..."
      - npm ci --no-audit --no-fund

  build:
    commands:
      - echo "BUILD: Preparing and executing build script..."
      # This script contains all logic to prevent YAML syntax errors.
      - |
        cat > ci-build.sh << 'SH'
        #!/usr/bin/env bash
        set -euo pipefail

        echo "--- PRE-BUILD STEPS ---"
        echo "Cleaning cache and removing old files..."
        npm cache clean --force
        rm -f src/lib/auth.ts || true

        echo "Setting package versions..."
        npm pkg set devDependencies.@eslint/eslintrc="^3.1.0"
        npm pkg set dependencies.recharts="^2.12.7" dependencies.lucide-react="^0.452.0"

        echo "--- BUILD STEPS ---"
        echo "Logging in to Docker Hub..."
        echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

        echo "Applying database migrations..."
        npx prisma migrate deploy

        echo "Generating Prisma Client..."
        npx prisma generate

        echo "Building Docker image..."
        COMMIT_HASH=$(git rev-parse --short HEAD)
        ECR_IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"
        
        docker build \
          --build-arg GIT_COMMIT_HASH="$COMMIT_HASH" \
          --build-arg DATABASE_URL="$DATABASE_URL" \
          --build-arg EMAIL_SERVER_HOST="$EMAIL_SERVER_HOST" \
          --build-arg EMAIL_SERVER_PORT="$EMAIL_SERVER_PORT" \
          --build-arg EMAIL_SERVER_USER="$EMAIL_SERVER_USER" \
          --build-arg EMAIL_SERVER_PASSWORD="$EMAIL_SERVER_PASSWORD" \
          --build-arg EMAIL_FROM="$EMAIL_FROM" \
          --build-arg NEXTAUTH_URL="$NEXTAUTH_URL" \
          --build-arg AUTH_URL="$NEXTAUTH_URL" \
          --build-arg NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
          --build-arg AUTH_TRUST_HOST="true" \
          --build-arg GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
          --build-arg GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" \
          --build-arg AZURE_AD_CLIENT_ID="$AZURE_AD_CLIENT_ID" \
          --build-arg AZURE_AD_CLIENT_SECRET="$AZURE_AD_CLIENT_SECRET" \
          --build-arg AZURE_AD_TENANT_ID="$AZURE_AD_TENANT_ID" \
          -t "$ECR_IMAGE_URI:$COMMIT_HASH" \
          -t "$ECR_IMAGE_URI:latest" .

        echo "Pushing image to ECR..."
        aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_IMAGE_URI"
        docker push "$ECR_IMAGE_URI:$COMMIT_HASH"
        docker push "$ECR_IMAGE_URI:latest"

        echo "Creating image definitions file..."
        printf '[{"name":"%s","imageUri":"%s:%s"}]' "$CONTAINER_NAME" "$ECR_IMAGE_URI" "$COMMIT_HASH" > imagedefinitions.json
        cat imagedefinitions.json
        SH
      - chmod +x ci-build.sh
      - bash ci-build.sh

  post_build:
    commands:
      - echo "POST_BUILD: Build complete. Deployment will be handled by CodePipeline."

artifacts:
  files:
    - imagedefinitions.json
