version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID     : "586359898361"
    AWS_DEFAULT_REGION : "ca-central-1"
    IMAGE_REPO_NAME    : "nartex-next"

    NEXTAUTH_URL       : "http://localhost:3000"
    NEXTAUTH_SECRET    : "aK9mX2vL8pQ4rN6sT1wE5yU3iO7aB0cF9dG8hJ2kM5nP1"

    EMAIL_SERVER_HOST  : "smtp.gmail.com"
    EMAIL_SERVER_PORT  : "587"
    EMAIL_SERVER_USER  : "n.labranche@nartex.ca"
    EMAIL_FROM         : "Nartex <noreply@nartex.ca>"

  secrets-manager:
    DATABASE_URL          : nartex-db-credentials
    EMAIL_SERVER_PASSWORD : EMAIL_SERVER_PASSWORD

phases:
  install:
    runtime-versions: { nodejs: 18 }
    commands:
      - echo "📦  INSTALL – installing Node dependencies"
      - npm ci

  pre_build:
    commands:
      - echo "📜  Running Prisma migrations"
      - npx prisma migrate deploy

      - echo "🔑  PRE_BUILD – logging in to Amazon ECR"
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

  build:
    commands:
      - echo "🏗  BUILD – resolving commit hash"
      - COMMIT_HASH=$(git rev-parse --short HEAD)

      - printf '%s\n' \
          "DATABASE_URL=$DATABASE_URL" \
          "EMAIL_SERVER_HOST=$EMAIL_SERVER_HOST" \
          "EMAIL_SERVER_PORT=$EMAIL_SERVER_PORT" \
          "EMAIL_SERVER_USER=$EMAIL_SERVER_USER" \
          "EMAIL_SERVER_PASSWORD=$EMAIL_SERVER_PASSWORD" \
          "EMAIL_FROM=$EMAIL_FROM" \
          "NEXTAUTH_URL=$NEXTAUTH_URL" \
          "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" \
        > .env.production

      - echo "🏗  BUILD – building & tagging Docker image"
      - |
        ECR_IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"
        docker build -t "$ECR_IMAGE_URI:$COMMIT_HASH" -t "$ECR_IMAGE_URI:latest" .

      - echo "📤  Pushing both tags to ECR"
      - docker push "$ECR_IMAGE_URI:$COMMIT_HASH"
      - docker push "$ECR_IMAGE_URI:latest"

  post_build:
    commands:
      - echo '🔄  POST_BUILD – redeploying ECS service (force pull of :latest)'
      - |
        aws ecs update-service \
          --cluster nartex-cluster \
          --service nartex-next-service \
          --force-new-deployment \
          --desired-count 2 \
          --deployment-configuration maximumPercent=200,minimumHealthyPercent=50,deploymentCircuitBreaker={enable=true,rollback=true} \
          --region $AWS_DEFAULT_REGION

artifacts:
  files:
    - imagedefinitions.json
