version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ca-central-1"
    AWS_ACCOUNT_ID: "586359898361"
    IMAGE_REPO_NAME: "nartex-next"
    # Must match the "name" field in your Task Definition container.
    CONTAINER_NAME: "nextjs"
    NEXTAUTH_URL: "https://app.nartex.ca"
    EMAIL_SERVER_HOST: "smtp.gmail.com"
    EMAIL_SERVER_PORT: "587"
    EMAIL_SERVER_USER: "n.labranche@nartex.ca"
    EMAIL_FROM: "Nartex <noreply@nartex.ca>"
    AZURE_AD_TENANT_ID: "organizations"

  secrets-manager:
    DATABASE_URL:           nartex/prod/env:DATABASE_URL
    EMAIL_SERVER_PASSWORD:  nartex/prod/env:EMAIL_SERVER_PASSWORD
    NEXTAUTH_SECRET:        nartex/prod/env:NEXTAUTH_SECRET
    GOOGLE_CLIENT_ID:       nartex/prod/env:GOOGLE_CLIENT_ID
    GOOGLE_CLIENT_SECRET:   nartex/prod/env:GOOGLE_CLIENT_SECRET
    AZURE_AD_CLIENT_ID:     nartex/prod/env:AZURE_AD_CLIENT_ID
    AZURE_AD_CLIENT_SECRET: nartex/prod/env:AZURE_AD_CLIENT_SECRET
    RDS_CREDENTIALS:        nartex/prod/rds-credentials

phases:
  pre_build:
    commands:
      - echo "📜 PRE_BUILD – preparing environment and logging into ECR"
      - |
        # Login to ECR first
        aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      
      - echo "🔧 PRE_BUILD – Setting up commit hash"
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - echo "COMMIT_HASH=$COMMIT_HASH"
      - ECR_IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME"

  build:
    commands:
      - echo "🚀 BUILD – Running Prisma migrations directly in Docker build"
      - echo "🐳 BUILD – Building Docker image with all environment variables"
      - |
        # Create a temporary .env file for the Docker build context
        # This ensures the build has access to all required environment variables
        cat > .env.production << EOF
        DATABASE_URL=$DATABASE_URL
        EMAIL_SERVER_HOST=$EMAIL_SERVER_HOST
        EMAIL_SERVER_PORT=$EMAIL_SERVER_PORT
        EMAIL_SERVER_USER=$EMAIL_SERVER_USER
        EMAIL_SERVER_PASSWORD=$EMAIL_SERVER_PASSWORD
        EMAIL_FROM=$EMAIL_FROM
        NEXTAUTH_URL=$NEXTAUTH_URL
        NEXTAUTH_SECRET=$NEXTAUTH_SECRET
        GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
        GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
        AZURE_AD_CLIENT_ID=$AZURE_AD_CLIENT_ID
        AZURE_AD_CLIENT_SECRET=$AZURE_AD_CLIENT_SECRET
        AZURE_AD_TENANT_ID=$AZURE_AD_TENANT_ID
        EOF
      
      - echo "🐳 BUILD – Building Docker image"
      - |
        docker build --no-cache --pull \
          --build-arg GIT_COMMIT_HASH="$COMMIT_HASH" \
          --build-arg DATABASE_URL="$DATABASE_URL" \
          --build-arg EMAIL_SERVER_HOST="$EMAIL_SERVER_HOST" \
          --build-arg EMAIL_SERVER_PORT="$EMAIL_SERVER_PORT" \
          --build-arg EMAIL_SERVER_USER="$EMAIL_SERVER_USER" \
          --build-arg EMAIL_SERVER_PASSWORD="$EMAIL_SERVER_PASSWORD" \
          --build-arg EMAIL_FROM="$EMAIL_FROM" \
          --build-arg NEXTAUTH_URL="$NEXTAUTH_URL" \
          --build-arg NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
          --build-arg GOOGLE_CLIENT_ID="$GOOGLE_CLIENT_ID" \
          --build-arg GOOGLE_CLIENT_SECRET="$GOOGLE_CLIENT_SECRET" \
          --build-arg AZURE_AD_CLIENT_ID="$AZURE_AD_CLIENT_ID" \
          --build-arg AZURE_AD_CLIENT_SECRET="$AZURE_AD_CLIENT_SECRET" \
          --build-arg AZURE_AD_TENANT_ID="$AZURE_AD_TENANT_ID" \
          -t "$ECR_IMAGE_URI:$COMMIT_HASH" \
          -t "$ECR_IMAGE_URI:latest" .
      
      - echo "🧾 BUILD – Writing imagedefinitions.json artifact"
      - |
        printf '[{"name":"%s","imageUri":"%s"}]\n' \
          "$CONTAINER_NAME" "$ECR_IMAGE_URI:$COMMIT_HASH" > imagedefinitions.json
        cat imagedefinitions.json
      
      - echo "📤 BUILD – Pushing images to ECR"
      - docker push "$ECR_IMAGE_URI:$COMMIT_HASH"
      - docker push "$ECR_IMAGE_URI:latest"
      
      - echo "🧹 BUILD – Cleaning up sensitive files"
      - rm -f .env.production

  post_build:
    commands:
      - echo "✅ POST_BUILD – Build completed on $(date)"
      - echo "🔄 POST_BUILD – Forcing new ECS deployment"
      - |
        aws ecs update-service \
          --cluster nartex-cluster \
          --service nartex-next-service \
          --force-new-deployment \
          --region $AWS_DEFAULT_REGION \
          || echo "⚠️ ECS update-service failed (service may not exist yet)"
      - echo "✨ POST_BUILD – Deployment triggered successfully"

artifacts:
  files:
    - imagedefinitions.json
