version: 0.2

# =================================================================
# ENVIRONMENT VARIABLES
# =================================================================
env:
  variables:
    # Set to your ECR repository name
    IMAGE_REPO_NAME: "nartex-next"
    IMAGE_TAG: "latest"
  secrets-manager:
    # Fetches the plaintext secret from Secrets Manager
    DATABASE_URL: nartex-db-credentials

# =================================================================
# BUILD PHASES
# =================================================================
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Phase: install - Installing project dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Phase: pre_build - Running Prisma migrations..."
      - npx prisma migrate deploy
      - echo "Prisma migrations completed successfully."
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Phase: build - Building, tagging, and pushing the Docker image..."
      - ECR_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker build -t $ECR_IMAGE_URI .
      - docker push $ECR_IMAGE_URI
      - echo "Docker image pushed successfully to $ECR_IMAGE_URI"

  post_build:
    commands:
      - echo "Phase: post_build - Creating image definitions file for ECS deployment..."
      # UPDATED: This now correctly uses 'nextjs' as the container name
      - printf '[{"name":"nextjs","imageUri":"%s"}]' $ECR_IMAGE_URI > imagedefinitions.json
      - echo "Generated imagedefinitions.json:"
      - cat imagedefinitions.json

# =================================================================
# ARTIFACTS
# =================================================================
# This artifact will be used by AWS CodePipeline to deploy to ECS
artifacts:
  files:
    - imagedefinitions.json