services:
  nartex-app:
    build: .
    image: nartex-next-prod
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      EMAIL_SERVER_HOST: "${EMAIL_SERVER_HOST}"
      EMAIL_SERVER_PORT: "${EMAIL_SERVER_PORT}"
      EMAIL_SERVER_USER: "${EMAIL_SERVER_USER}"
      EMAIL_SERVER_PASSWORD: "${EMAIL_SERVER_PASSWORD}"
      EMAIL_FROM: "${EMAIL_FROM}"
      PORT: "3000"
